spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/architecture
    username: sa
    password:
  driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

jwt:
  secret: MlwEyVEsYt9V7zq93TejMnVXyzblYcfPQye37f7MGVA9XkHaadb32dF
  access-token-validity-in-seconds: 600 # 10min